### ISSUE TITLE
Undefined propert afterValidationMutator

### ISSUE THREAD

**Issue by uqjohart** [eighty9nine/filament-excel-import#25]
PHP: 8.2.22
Laravel: 10.48.20
ErrorException: Undefined property: EightyNine\ExcelImport\DefaultImport::$afterValidationMutator

Fresh install of the plugin. 

Full log:
[2024-08-29 10:24:49] local.ERROR: Undefined property: EightyNine\ExcelImport\DefaultImport::$afterValidationMutator {"userId":1,"exception":"[object] (ErrorException(code: 0): Undefined property: EightyNine\\ExcelImport\\DefaultImport::$afterValidationMutator at /var/www/html/vendor/eightynine/filament-excel-import/src/DefaultImport.php:45)

**Comment by uqjohart** [comment]
Looks like there is just a missing function... to get it working for now I have just commented out the feature. Not a long term solution. 

```swift
    public function setAfterValidationMutator(Closure $closure): void
    {
        // $this->afterValidationMutator = $closure;
    }

    public function collection(Collection $collection)
    {
        if (is_callable($this->collectionMethod)) {
            $collection = call_user_func(
                $this->collectionMethod,
                $this->model,
                $collection,
                $this->additionalData,
                // $this->afterValidationMutator
            );
        } else {
            foreach ($collection as $row) {
                $data = $row->toArray();
                if (filled($this->additionalData)) {
                    $data = array_merge($data, $this->additionalData);
                }
                // if($this->afterValidationMutator){
                //     $data = call_user_func(
                //         $this->afterValidationMutator,
                //         $data
                //     );
                // }
                $this->model::create($data);
            }
        }
        ```

**Comment by uqjohart** [comment]
I tried added this ti the top... thought maybe I can dodgy it up... 
```
protected ?Closure $afterValidationMutator = null;
```
But looks like both mutateBeforeValidationUsing() and mutateAfterValidationUsing() are not firing at all. And the data cant be mutated.

**Comment by eighty9nine** [comment]
The error has been fixed in the new release, but for the case of the data not being mutated, can you please share your code(the import action)

**Comment by uqjohart** [comment]
> The error has been fixed in the new release, but for the case of the data not being mutated, can you please share your code(the import action)

I just did a fresh remove and readd, as well as a total fresh add on a new project. Results:
1. a standard import works now without throwing the error and without my dodgy hack. 
2, The mutateBeforeValidationUsing() still doesnt seem to be firing at all... maybe I am doing it wrong?

Hear is a silly example that should turn the names given into email which should pass the validation. It seems to do nothing.

```swift

namespace App\Filament\Resources\RoleResource\Pages;

use App\Filament\Resources\RoleResource;
use Filament\Actions;
use Filament\Resources\Pages\ListRecords;
use Archilex\AdvancedTables\AdvancedTables;

class ListRoles extends ListRecords
{
    use AdvancedTables;
    protected static string $resource = RoleResource::class;

    protected function getHeaderActions(): array
    {
        return [
            \EightyNine\ExcelImport\ExcelImportAction::make()
                ->mutateBeforeValidationUsing(function (array $data): array {
                    dd($data); // This doesn't fire at all :S
                    foreach ($data as $key => $cause) {
                        $data[$key]['name'] = $cause['name'] . '@test.com';
                    }
                    return $data;
                })
                ->validateUsing([
                    'name' => 'required|email',
                ]),
            Actions\CreateAction::make(),
        ];
    }
}
```

![image](https://github.com/user-attachments/assets/506cadb6-42ef-46cd-8c49-585a320bdf64)

**Comment by uqjohart** [comment]
Second example: Just adding some extra text on the end before validation. 
This adds but the text is not changed

```swift
namespace App\Filament\Resources\RoleResource\Pages;

use App\Filament\Resources\RoleResource;
use Filament\Actions;
use Filament\Resources\Pages\ListRecords;
use Archilex\AdvancedTables\AdvancedTables;

class ListRoles extends ListRecords
{
    use AdvancedTables;
    protected static string $resource = RoleResource::class;

    protected function getHeaderActions(): array
    {
        return [
            \EightyNine\ExcelImport\ExcelImportAction::make()
                ->mutateBeforeValidationUsing(function (array $data): array {
                    // dd($data); // This doesn't fire at all :S
                    foreach ($data as $key => $cause) {
                        $data[$key]['name'] = $cause['name'] . 'some extra text';
                    }
                    return $data;
                })
                ->validateUsing([
                    'name' => 'required',
                ]),
            Actions\CreateAction::make(),
        ];
    }
}
```
![image](https://github.com/user-attachments/assets/6995e76a-430e-4dbc-b414-c789e6f6e695)

**Comment by eighty9nine** [comment]
this has been fixed in the latest update, please find the details in [the documentation](https://github.com/eighty9nine/filament-excel-import/tree/3.1.5#mutating-data-before-and-after-validation)
